name: Deploy AWS Image Processor

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # NEW: Build image processor lambda
      - name: Build image processor package
        working-directory: image-processing-pipeline/lambda/image_processor
        run: |
          pip install -r requirements.txt -t .
          zip -r ../../image_processor.zip .

      # NEW: Build DLQ reprocessor lambda
      - name: Build DLQ reprocessor package
        working-directory: image-processing-pipeline/lambda/dlq_reprocessor
        run: |
          zip -r ../../dlq_reprocessor.zip .


      - name: Build API Lambda package
        working-directory: backend/api
        run: |
          zip function.zip handler.py    
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Terraform Init
        working-directory: image-processing-pipeline
        run: terraform init
      
      - name: Terraform Apply
        working-directory: image-processing-pipeline
        run: terraform apply -auto-approve